//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.15 at 05:11:59 PM CET 
//


package eu.trentorise.smartcampus.service.trentinofamiglia.distretti.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Url_alias" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Coordinate">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Latitudine" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="Longitudine" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OrganizzazioniAderenti">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Aderente" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Url_alias" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                             &lt;element name="Nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Abstract" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Indirizzo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Telefono" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SitoWeb" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                             &lt;element name="Logo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Coordinate">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Latitudine" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="Longitudine" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="MarchioAudit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MarchioFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CategoriaMarchioFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Coordinatore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Proponente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ProgrammiDiLavoro">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ProgrammaDiLavoro" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Url_alias" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                             &lt;element name="AttivitaDistretto">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Attivita" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Referenti" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Tempi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Azioni">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="Azione" maxOccurs="unbounded" minOccurs="0">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;sequence>
 *                                                                     &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                                     &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                                     &lt;element name="Obiettivo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                                     &lt;element name="Referenti" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                                     &lt;element name="Tempi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                                     &lt;element name="Tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                                   &lt;/sequence>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="anno" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "urlAlias",
    "titolo",
    "descrizione",
    "coordinate",
    "organizzazioniAderenti",
    "programmiDiLavoro"
})
@XmlRootElement(name = "Distretto")
public class Distretto {

    @XmlElement(name = "Url_alias", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String urlAlias;
    @XmlElement(name = "Titolo", required = true)
    protected String titolo;
    @XmlElement(name = "Descrizione", required = true)
    protected String descrizione;
    @XmlElement(name = "Coordinate", required = true)
    protected Distretto.Coordinate coordinate;
    @XmlElement(name = "OrganizzazioniAderenti", required = true)
    protected Distretto.OrganizzazioniAderenti organizzazioniAderenti;
    @XmlElement(name = "ProgrammiDiLavoro", required = true)
    protected Distretto.ProgrammiDiLavoro programmiDiLavoro;

    /**
     * Gets the value of the urlAlias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlAlias() {
        return urlAlias;
    }

    /**
     * Sets the value of the urlAlias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlAlias(String value) {
        this.urlAlias = value;
    }

    /**
     * Gets the value of the titolo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitolo() {
        return titolo;
    }

    /**
     * Sets the value of the titolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitolo(String value) {
        this.titolo = value;
    }

    /**
     * Gets the value of the descrizione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * Sets the value of the descrizione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescrizione(String value) {
        this.descrizione = value;
    }

    /**
     * Gets the value of the coordinate property.
     * 
     * @return
     *     possible object is
     *     {@link Distretto.Coordinate }
     *     
     */
    public Distretto.Coordinate getCoordinate() {
        return coordinate;
    }

    /**
     * Sets the value of the coordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Distretto.Coordinate }
     *     
     */
    public void setCoordinate(Distretto.Coordinate value) {
        this.coordinate = value;
    }

    /**
     * Gets the value of the organizzazioniAderenti property.
     * 
     * @return
     *     possible object is
     *     {@link Distretto.OrganizzazioniAderenti }
     *     
     */
    public Distretto.OrganizzazioniAderenti getOrganizzazioniAderenti() {
        return organizzazioniAderenti;
    }

    /**
     * Sets the value of the organizzazioniAderenti property.
     * 
     * @param value
     *     allowed object is
     *     {@link Distretto.OrganizzazioniAderenti }
     *     
     */
    public void setOrganizzazioniAderenti(Distretto.OrganizzazioniAderenti value) {
        this.organizzazioniAderenti = value;
    }

    /**
     * Gets the value of the programmiDiLavoro property.
     * 
     * @return
     *     possible object is
     *     {@link Distretto.ProgrammiDiLavoro }
     *     
     */
    public Distretto.ProgrammiDiLavoro getProgrammiDiLavoro() {
        return programmiDiLavoro;
    }

    /**
     * Sets the value of the programmiDiLavoro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Distretto.ProgrammiDiLavoro }
     *     
     */
    public void setProgrammiDiLavoro(Distretto.ProgrammiDiLavoro value) {
        this.programmiDiLavoro = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Latitudine" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="Longitudine" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "latitudine",
        "longitudine"
    })
    public static class Coordinate {

        @XmlElement(name = "Latitudine")
        protected float latitudine;
        @XmlElement(name = "Longitudine")
        protected float longitudine;

        /**
         * Gets the value of the latitudine property.
         * 
         */
        public float getLatitudine() {
            return latitudine;
        }

        /**
         * Sets the value of the latitudine property.
         * 
         */
        public void setLatitudine(float value) {
            this.latitudine = value;
        }

        /**
         * Gets the value of the longitudine property.
         * 
         */
        public float getLongitudine() {
            return longitudine;
        }

        /**
         * Sets the value of the longitudine property.
         * 
         */
        public void setLongitudine(float value) {
            this.longitudine = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Aderente" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Url_alias" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                   &lt;element name="Nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Abstract" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Indirizzo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Telefono" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SitoWeb" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                   &lt;element name="Logo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Coordinate">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Latitudine" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="Longitudine" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="MarchioAudit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="MarchioFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CategoriaMarchioFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Coordinatore" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Proponente" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "aderente"
    })
    public static class OrganizzazioniAderenti {

        @XmlElement(name = "Aderente")
        protected List<Distretto.OrganizzazioniAderenti.Aderente> aderente;

        /**
         * Gets the value of the aderente property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aderente property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAderente().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Distretto.OrganizzazioniAderenti.Aderente }
         * 
         * 
         */
        public List<Distretto.OrganizzazioniAderenti.Aderente> getAderente() {
            if (aderente == null) {
                aderente = new ArrayList<Distretto.OrganizzazioniAderenti.Aderente>();
            }
            return this.aderente;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Url_alias" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *         &lt;element name="Nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Abstract" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Indirizzo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Telefono" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SitoWeb" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *         &lt;element name="Logo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Coordinate">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Latitudine" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="Longitudine" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="MarchioAudit" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="MarchioFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CategoriaMarchioFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Coordinatore" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Proponente" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "urlAlias",
            "nome",
            "_abstract",
            "indirizzo",
            "telefono",
            "fax",
            "email",
            "sitoWeb",
            "logo",
            "coordinate",
            "marchioAudit",
            "marchioFamily",
            "categoriaMarchioFamily",
            "coordinatore",
            "proponente"
        })
        public static class Aderente {

            @XmlElement(name = "Url_alias", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String urlAlias;
            @XmlElement(name = "Nome", required = true)
            protected String nome;
            @XmlElement(name = "Abstract", required = true)
            protected String _abstract;
            @XmlElement(name = "Indirizzo", required = true)
            protected String indirizzo;
            @XmlElement(name = "Telefono", required = true)
            protected String telefono;
            @XmlElement(name = "Fax", required = true)
            protected String fax;
            @XmlElement(name = "Email", required = true)
            protected String email;
            @XmlElement(name = "SitoWeb", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String sitoWeb;
            @XmlElement(name = "Logo", required = true)
            protected String logo;
            @XmlElement(name = "Coordinate", required = true)
            protected Distretto.OrganizzazioniAderenti.Aderente.Coordinate coordinate;
            @XmlElement(name = "MarchioAudit", required = true)
            protected String marchioAudit;
            @XmlElement(name = "MarchioFamily", required = true)
            protected String marchioFamily;
            @XmlElement(name = "CategoriaMarchioFamily", required = true)
            protected String categoriaMarchioFamily;
            @XmlElement(name = "Coordinatore", required = true)
            protected String coordinatore;
            @XmlElement(name = "Proponente", required = true)
            protected String proponente;

            /**
             * Gets the value of the urlAlias property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrlAlias() {
                return urlAlias;
            }

            /**
             * Sets the value of the urlAlias property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrlAlias(String value) {
                this.urlAlias = value;
            }

            /**
             * Gets the value of the nome property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNome() {
                return nome;
            }

            /**
             * Sets the value of the nome property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNome(String value) {
                this.nome = value;
            }

            /**
             * Gets the value of the abstract property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAbstract() {
                return _abstract;
            }

            /**
             * Sets the value of the abstract property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAbstract(String value) {
                this._abstract = value;
            }

            /**
             * Gets the value of the indirizzo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIndirizzo() {
                return indirizzo;
            }

            /**
             * Sets the value of the indirizzo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIndirizzo(String value) {
                this.indirizzo = value;
            }

            /**
             * Gets the value of the telefono property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTelefono() {
                return telefono;
            }

            /**
             * Sets the value of the telefono property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTelefono(String value) {
                this.telefono = value;
            }

            /**
             * Gets the value of the fax property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFax() {
                return fax;
            }

            /**
             * Sets the value of the fax property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFax(String value) {
                this.fax = value;
            }

            /**
             * Gets the value of the email property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmail() {
                return email;
            }

            /**
             * Sets the value of the email property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmail(String value) {
                this.email = value;
            }

            /**
             * Gets the value of the sitoWeb property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSitoWeb() {
                return sitoWeb;
            }

            /**
             * Sets the value of the sitoWeb property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSitoWeb(String value) {
                this.sitoWeb = value;
            }

            /**
             * Gets the value of the logo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLogo() {
                return logo;
            }

            /**
             * Sets the value of the logo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLogo(String value) {
                this.logo = value;
            }

            /**
             * Gets the value of the coordinate property.
             * 
             * @return
             *     possible object is
             *     {@link Distretto.OrganizzazioniAderenti.Aderente.Coordinate }
             *     
             */
            public Distretto.OrganizzazioniAderenti.Aderente.Coordinate getCoordinate() {
                return coordinate;
            }

            /**
             * Sets the value of the coordinate property.
             * 
             * @param value
             *     allowed object is
             *     {@link Distretto.OrganizzazioniAderenti.Aderente.Coordinate }
             *     
             */
            public void setCoordinate(Distretto.OrganizzazioniAderenti.Aderente.Coordinate value) {
                this.coordinate = value;
            }

            /**
             * Gets the value of the marchioAudit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMarchioAudit() {
                return marchioAudit;
            }

            /**
             * Sets the value of the marchioAudit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMarchioAudit(String value) {
                this.marchioAudit = value;
            }

            /**
             * Gets the value of the marchioFamily property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMarchioFamily() {
                return marchioFamily;
            }

            /**
             * Sets the value of the marchioFamily property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMarchioFamily(String value) {
                this.marchioFamily = value;
            }

            /**
             * Gets the value of the categoriaMarchioFamily property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCategoriaMarchioFamily() {
                return categoriaMarchioFamily;
            }

            /**
             * Sets the value of the categoriaMarchioFamily property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCategoriaMarchioFamily(String value) {
                this.categoriaMarchioFamily = value;
            }

            /**
             * Gets the value of the coordinatore property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCoordinatore() {
                return coordinatore;
            }

            /**
             * Sets the value of the coordinatore property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCoordinatore(String value) {
                this.coordinatore = value;
            }

            /**
             * Gets the value of the proponente property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProponente() {
                return proponente;
            }

            /**
             * Sets the value of the proponente property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProponente(String value) {
                this.proponente = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Latitudine" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="Longitudine" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "latitudine",
                "longitudine"
            })
            public static class Coordinate {

                @XmlElement(name = "Latitudine")
                protected float latitudine;
                @XmlElement(name = "Longitudine")
                protected float longitudine;

                /**
                 * Gets the value of the latitudine property.
                 * 
                 */
                public float getLatitudine() {
                    return latitudine;
                }

                /**
                 * Sets the value of the latitudine property.
                 * 
                 */
                public void setLatitudine(float value) {
                    this.latitudine = value;
                }

                /**
                 * Gets the value of the longitudine property.
                 * 
                 */
                public float getLongitudine() {
                    return longitudine;
                }

                /**
                 * Sets the value of the longitudine property.
                 * 
                 */
                public void setLongitudine(float value) {
                    this.longitudine = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ProgrammaDiLavoro" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Url_alias" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                   &lt;element name="AttivitaDistretto">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Attivita" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Referenti" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Tempi" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Azioni">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="Azione" maxOccurs="unbounded" minOccurs="0">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;sequence>
     *                                                           &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                           &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                           &lt;element name="Obiettivo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                           &lt;element name="Referenti" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                           &lt;element name="Tempi" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                           &lt;element name="Tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                         &lt;/sequence>
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="anno" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "programmaDiLavoro"
    })
    public static class ProgrammiDiLavoro {

        @XmlElement(name = "ProgrammaDiLavoro")
        protected List<Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro> programmaDiLavoro;

        /**
         * Gets the value of the programmaDiLavoro property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the programmaDiLavoro property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProgrammaDiLavoro().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro }
         * 
         * 
         */
        public List<Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro> getProgrammaDiLavoro() {
            if (programmaDiLavoro == null) {
                programmaDiLavoro = new ArrayList<Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro>();
            }
            return this.programmaDiLavoro;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Url_alias" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *         &lt;element name="AttivitaDistretto">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Attivita" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Referenti" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Tempi" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Azioni">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="Azione" maxOccurs="unbounded" minOccurs="0">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;sequence>
         *                                                 &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                                 &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                                 &lt;element name="Obiettivo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                                 &lt;element name="Referenti" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                                 &lt;element name="Tempi" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                                 &lt;element name="Tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                               &lt;/sequence>
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="anno" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "urlAlias",
            "attivitaDistretto"
        })
        public static class ProgrammaDiLavoro {

            @XmlElement(name = "Url_alias", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String urlAlias;
            @XmlElement(name = "AttivitaDistretto", required = true)
            protected Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto attivitaDistretto;
            @XmlAttribute
            protected String anno;

            /**
             * Gets the value of the urlAlias property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrlAlias() {
                return urlAlias;
            }

            /**
             * Sets the value of the urlAlias property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrlAlias(String value) {
                this.urlAlias = value;
            }

            /**
             * Gets the value of the attivitaDistretto property.
             * 
             * @return
             *     possible object is
             *     {@link Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto }
             *     
             */
            public Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto getAttivitaDistretto() {
                return attivitaDistretto;
            }

            /**
             * Sets the value of the attivitaDistretto property.
             * 
             * @param value
             *     allowed object is
             *     {@link Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto }
             *     
             */
            public void setAttivitaDistretto(Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto value) {
                this.attivitaDistretto = value;
            }

            /**
             * Gets the value of the anno property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAnno() {
                return anno;
            }

            /**
             * Sets the value of the anno property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAnno(String value) {
                this.anno = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Attivita" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Referenti" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Tempi" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Azioni">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="Azione" maxOccurs="unbounded" minOccurs="0">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;sequence>
             *                                       &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                       &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                       &lt;element name="Obiettivo" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                       &lt;element name="Referenti" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                       &lt;element name="Tempi" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                       &lt;element name="Tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                     &lt;/sequence>
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "attivita"
            })
            public static class AttivitaDistretto {

                @XmlElement(name = "Attivita")
                protected List<Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita> attivita;

                /**
                 * Gets the value of the attivita property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the attivita property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAttivita().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita }
                 * 
                 * 
                 */
                public List<Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita> getAttivita() {
                    if (attivita == null) {
                        attivita = new ArrayList<Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita>();
                    }
                    return this.attivita;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Referenti" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Tempi" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Azioni">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="Azione" maxOccurs="unbounded" minOccurs="0">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;sequence>
                 *                             &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                             &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                             &lt;element name="Obiettivo" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                             &lt;element name="Referenti" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                             &lt;element name="Tempi" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                             &lt;element name="Tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                           &lt;/sequence>
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "titolo",
                    "descrizione",
                    "referenti",
                    "tempi",
                    "tags",
                    "azioni"
                })
                public static class Attivita {

                    @XmlElement(name = "Titolo", required = true)
                    protected String titolo;
                    @XmlElement(name = "Descrizione", required = true)
                    protected String descrizione;
                    @XmlElement(name = "Referenti", required = true)
                    protected String referenti;
                    @XmlElement(name = "Tempi", required = true)
                    protected String tempi;
                    @XmlElement(name = "Tags", required = true)
                    protected String tags;
                    @XmlElement(name = "Azioni", required = true)
                    protected Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni azioni;

                    /**
                     * Gets the value of the titolo property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTitolo() {
                        return titolo;
                    }

                    /**
                     * Sets the value of the titolo property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTitolo(String value) {
                        this.titolo = value;
                    }

                    /**
                     * Gets the value of the descrizione property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDescrizione() {
                        return descrizione;
                    }

                    /**
                     * Sets the value of the descrizione property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDescrizione(String value) {
                        this.descrizione = value;
                    }

                    /**
                     * Gets the value of the referenti property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getReferenti() {
                        return referenti;
                    }

                    /**
                     * Sets the value of the referenti property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setReferenti(String value) {
                        this.referenti = value;
                    }

                    /**
                     * Gets the value of the tempi property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTempi() {
                        return tempi;
                    }

                    /**
                     * Sets the value of the tempi property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTempi(String value) {
                        this.tempi = value;
                    }

                    /**
                     * Gets the value of the tags property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTags() {
                        return tags;
                    }

                    /**
                     * Sets the value of the tags property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTags(String value) {
                        this.tags = value;
                    }

                    /**
                     * Gets the value of the azioni property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni }
                     *     
                     */
                    public Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni getAzioni() {
                        return azioni;
                    }

                    /**
                     * Sets the value of the azioni property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni }
                     *     
                     */
                    public void setAzioni(Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni value) {
                        this.azioni = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="Azione" maxOccurs="unbounded" minOccurs="0">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;sequence>
                     *                   &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *                   &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *                   &lt;element name="Obiettivo" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *                   &lt;element name="Referenti" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *                   &lt;element name="Tempi" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *                   &lt;element name="Tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *                 &lt;/sequence>
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "azione"
                    })
                    public static class Azioni {

                        @XmlElement(name = "Azione")
                        protected List<Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni.Azione> azione;

                        /**
                         * Gets the value of the azione property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the azione property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getAzione().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni.Azione }
                         * 
                         * 
                         */
                        public List<Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni.Azione> getAzione() {
                            if (azione == null) {
                                azione = new ArrayList<Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni.Azione>();
                            }
                            return this.azione;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;sequence>
                         *         &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
                         *         &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
                         *         &lt;element name="Obiettivo" type="{http://www.w3.org/2001/XMLSchema}string"/>
                         *         &lt;element name="Referenti" type="{http://www.w3.org/2001/XMLSchema}string"/>
                         *         &lt;element name="Tempi" type="{http://www.w3.org/2001/XMLSchema}string"/>
                         *         &lt;element name="Tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
                         *       &lt;/sequence>
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "titolo",
                            "descrizione",
                            "obiettivo",
                            "referenti",
                            "tempi",
                            "tags"
                        })
                        public static class Azione {

                            @XmlElement(name = "Titolo", required = true)
                            protected String titolo;
                            @XmlElement(name = "Descrizione", required = true)
                            protected String descrizione;
                            @XmlElement(name = "Obiettivo", required = true)
                            protected String obiettivo;
                            @XmlElement(name = "Referenti", required = true)
                            protected String referenti;
                            @XmlElement(name = "Tempi", required = true)
                            protected String tempi;
                            @XmlElement(name = "Tags", required = true)
                            protected String tags;

                            /**
                             * Gets the value of the titolo property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getTitolo() {
                                return titolo;
                            }

                            /**
                             * Sets the value of the titolo property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setTitolo(String value) {
                                this.titolo = value;
                            }

                            /**
                             * Gets the value of the descrizione property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getDescrizione() {
                                return descrizione;
                            }

                            /**
                             * Sets the value of the descrizione property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setDescrizione(String value) {
                                this.descrizione = value;
                            }

                            /**
                             * Gets the value of the obiettivo property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getObiettivo() {
                                return obiettivo;
                            }

                            /**
                             * Sets the value of the obiettivo property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setObiettivo(String value) {
                                this.obiettivo = value;
                            }

                            /**
                             * Gets the value of the referenti property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getReferenti() {
                                return referenti;
                            }

                            /**
                             * Sets the value of the referenti property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setReferenti(String value) {
                                this.referenti = value;
                            }

                            /**
                             * Gets the value of the tempi property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getTempi() {
                                return tempi;
                            }

                            /**
                             * Sets the value of the tempi property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setTempi(String value) {
                                this.tempi = value;
                            }

                            /**
                             * Gets the value of the tags property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getTags() {
                                return tags;
                            }

                            /**
                             * Sets the value of the tags property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setTags(String value) {
                                this.tags = value;
                            }

                        }

                    }

                }

            }

        }

    }

}
