//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.15 at 05:11:59 PM CET 
//


package eu.trentorise.smartcampus.service.trentinofamiglia.distretti.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.trentorise.smartcampus.service.trentinofamiglia.distretti.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.trentorise.smartcampus.service.trentinofamiglia.distretti.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Distretto.OrganizzazioniAderenti.Aderente }
     * 
     */
    public Distretto.OrganizzazioniAderenti.Aderente createDistrettoOrganizzazioniAderentiAderente() {
        return new Distretto.OrganizzazioniAderenti.Aderente();
    }

    /**
     * Create an instance of {@link Distretto.ProgrammiDiLavoro }
     * 
     */
    public Distretto.ProgrammiDiLavoro createDistrettoProgrammiDiLavoro() {
        return new Distretto.ProgrammiDiLavoro();
    }

    /**
     * Create an instance of {@link Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita }
     * 
     */
    public Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita createDistrettoProgrammiDiLavoroProgrammaDiLavoroAttivitaDistrettoAttivita() {
        return new Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita();
    }

    /**
     * Create an instance of {@link Distretto.OrganizzazioniAderenti.Aderente.Coordinate }
     * 
     */
    public Distretto.OrganizzazioniAderenti.Aderente.Coordinate createDistrettoOrganizzazioniAderentiAderenteCoordinate() {
        return new Distretto.OrganizzazioniAderenti.Aderente.Coordinate();
    }

    /**
     * Create an instance of {@link Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto }
     * 
     */
    public Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto createDistrettoProgrammiDiLavoroProgrammaDiLavoroAttivitaDistretto() {
        return new Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto();
    }

    /**
     * Create an instance of {@link Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni.Azione }
     * 
     */
    public Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni.Azione createDistrettoProgrammiDiLavoroProgrammaDiLavoroAttivitaDistrettoAttivitaAzioniAzione() {
        return new Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni.Azione();
    }

    /**
     * Create an instance of {@link Distretto.Coordinate }
     * 
     */
    public Distretto.Coordinate createDistrettoCoordinate() {
        return new Distretto.Coordinate();
    }

    /**
     * Create an instance of {@link Distretto.OrganizzazioniAderenti }
     * 
     */
    public Distretto.OrganizzazioniAderenti createDistrettoOrganizzazioniAderenti() {
        return new Distretto.OrganizzazioniAderenti();
    }

    /**
     * Create an instance of {@link Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro }
     * 
     */
    public Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro createDistrettoProgrammiDiLavoroProgrammaDiLavoro() {
        return new Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro();
    }

    /**
     * Create an instance of {@link Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni }
     * 
     */
    public Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni createDistrettoProgrammiDiLavoroProgrammaDiLavoroAttivitaDistrettoAttivitaAzioni() {
        return new Distretto.ProgrammiDiLavoro.ProgrammaDiLavoro.AttivitaDistretto.Attivita.Azioni();
    }

    /**
     * Create an instance of {@link Distretto }
     * 
     */
    public Distretto createDistretto() {
        return new Distretto();
    }

}
