//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.24 at 11:46:57 AM CET 
//


package eu.trentorise.smartcampus.service.trentinofamiglia.distretti2014.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.trentorise.smartcampus.service.trentinofamiglia.distretti2014.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaComuniComune_QNAME = new QName("", "Comune");
    private final static QName _OrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaModuloDiIscrizioneDimensione_QNAME = new QName("", "Dimensione");
    private final static QName _OrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaModuloDiIscrizioneFileUrl_QNAME = new QName("", "FileUrl");
    private final static QName _OrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaModuloDiIscrizioneNomeFile_QNAME = new QName("", "NomeFile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.trentorise.smartcampus.service.trentinofamiglia.distretti2014.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni.Comune }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni.Comune createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaComuniComune() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni.Comune();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaComuni() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.VincoloDiResidenza }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.VincoloDiResidenza createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaVincoloDiResidenza() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.VincoloDiResidenza();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.ModuloDiIscrizione }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.ModuloDiIscrizione createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaModuloDiIscrizione() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.ModuloDiIscrizione();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.TipoOrganizzazione }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.TipoOrganizzazione createOrganizzazioniEGFListOrganizzazioneTipoOrganizzazione() {
        return new OrganizzazioniEGFList.Organizzazione.TipoOrganizzazione();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList }
     * 
     */
    public OrganizzazioniEGFList createOrganizzazioniEGFList() {
        return new OrganizzazioniEGFList();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.Comune.Coordinate }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.Comune.Coordinate createOrganizzazioniEGFListOrganizzazioneComuneCoordinate() {
        return new OrganizzazioniEGFList.Organizzazione.Comune.Coordinate();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.GiorniSettimana.Giorno }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.GiorniSettimana.Giorno createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaGiorniSettimanaGiorno() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.GiorniSettimana.Giorno();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.GiorniSettimana }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.GiorniSettimana createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaGiorniSettimana() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.GiorniSettimana();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Frequenza }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Frequenza createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaFrequenza() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Frequenza();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.Coordinate }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.Coordinate createOrganizzazioniEGFListOrganizzazioneCoordinate() {
        return new OrganizzazioniEGFList.Organizzazione.Coordinate();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Referenti }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Referenti createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaReferenti() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Referenti();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaList() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione createOrganizzazioniEGFListOrganizzazione() {
        return new OrganizzazioniEGFList.Organizzazione();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni.Comune.Coordinate }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni.Comune.Coordinate createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaComuniComuneCoordinate() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni.Comune.Coordinate();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamiglia() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.MesiSvolgimento.Mese }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.MesiSvolgimento.Mese createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaMesiSvolgimentoMese() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.MesiSvolgimento.Mese();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Referenti.Referente }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Referenti.Referente createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaReferentiReferente() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Referenti.Referente();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.MesiSvolgimento }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.MesiSvolgimento createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaMesiSvolgimento() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.MesiSvolgimento();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.TipoCosto }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.TipoCosto createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaTipoCosto() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.TipoCosto();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.TipoAttivita }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.TipoAttivita createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaTipoAttivita() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.TipoAttivita();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.FasciaDiEta }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.FasciaDiEta createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaFasciaDiEta() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.FasciaDiEta();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.Comune }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.Comune createOrganizzazioniEGFListOrganizzazioneComune() {
        return new OrganizzazioniEGFList.Organizzazione.Comune();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.FasciaDiEta.Fascia }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.FasciaDiEta.Fascia createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaFasciaDiEtaFascia() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.FasciaDiEta.Fascia();
    }

    /**
     * Create an instance of {@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.OrganizzazioneREF }
     * 
     */
    public OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.OrganizzazioneREF createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaOrganizzazioneREF() {
        return new OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.OrganizzazioneREF();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni.Comune }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Comune", scope = OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni.class)
    public JAXBElement<OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni.Comune> createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaComuniComune(OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni.Comune value) {
        return new JAXBElement<OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni.Comune>(_OrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaComuniComune_QNAME, OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni.Comune.class, OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.Comuni.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Dimensione", scope = OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.ModuloDiIscrizione.class)
    public JAXBElement<String> createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaModuloDiIscrizioneDimensione(String value) {
        return new JAXBElement<String>(_OrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaModuloDiIscrizioneDimensione_QNAME, String.class, OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.ModuloDiIscrizione.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FileUrl", scope = OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.ModuloDiIscrizione.class)
    public JAXBElement<String> createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaModuloDiIscrizioneFileUrl(String value) {
        return new JAXBElement<String>(_OrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaModuloDiIscrizioneFileUrl_QNAME, String.class, OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.ModuloDiIscrizione.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NomeFile", scope = OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.ModuloDiIscrizione.class)
    public JAXBElement<String> createOrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaModuloDiIscrizioneNomeFile(String value) {
        return new JAXBElement<String>(_OrganizzazioniEGFListOrganizzazioneAttivitaEstateGiovaniEFamigliaListAttivitaEstateGiovaniEFamigliaModuloDiIscrizioneNomeFile_QNAME, String.class, OrganizzazioniEGFList.Organizzazione.AttivitaEstateGiovaniEFamigliaList.AttivitaEstateGiovaniEFamiglia.ModuloDiIscrizione.class, value);
    }

}
