//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.16 at 08:55:09 PM CEST 
//


package eu.trentorise.smartcampus.service.trentinofamiglia.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TAB_org" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ID_org" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Nome_organizzazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Telefono_x0020_fisso_x0020__x0028_organizzazione_x0029_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Telefono_x0020_mobile_x0020__x0028_organizzazione_x0029_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Sito_x0020_web_x0020__x0028_organizzazione_x0029_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Email_x0020__x0028_organizzazione_x0029_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="TAB_Attività" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ID_Attività_Contatore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Id_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ID_racc_org" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Nome_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Tipo_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Descrizione_x0020_sintetica_x0020_dell_x0027_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Data_x0020_inizio_x0020_periodo_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Data_x0020_fine_x0020_periodo_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Frequenza" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Orari_x0020__x002F__x0020_periodicità_x002F__x0020_turni_x0020_di_x0020_svolgimento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="L_x0027_attività_x0020_si_x0020_svolge_x0020_nei_x0020_seguenti_x0020_giorni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Sede_x002F_i_x0020_presso_x0020_cui_x0020_si_x0020_svolgerà_x0020_l_x0027_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Tipo_x0020_di_x0020_attività_x0020__x0028_diurna_x002F_residenziale_x0029_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Tipo_x0020_di_x0020_costo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Specifiche_x0020_sul_x0020_costo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Fascia_x002F_e_x0020_di_x0020_età_x0020_destinatari" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Note_x0020_su_x0020_età_x0020_dei_x0020_destinatari" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Vincoli_x0020_di_x0020_residenza_x0020_dei_x0020_destinatari" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Referenti_x0020_che_x0020_possono_x0020_fornire_x0020_informazioni_x0020_su_x0020_questa_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Modalità_x0020_e_x0020_tempi_x0020_di_x0020_iscrizione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="L_x0027_attività_x0020_è_x0020_marchiata_x0020__x0022_Family_x0020_in_x0020_Trentino_x0022__x003F_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Scheda" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="TAb_territorio" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ID_Tab_Comuni_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="ID_RACCORDO_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Comuni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Comunità_valle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="TB_mese" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ID_Mese" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="ID_RACCORDO_Attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Giugno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Luglio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Agosto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Settembre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="generated" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tabOrg"
})
@XmlRootElement(name = "dataroot")
public class Dataroot {

    @XmlElement(name = "TAB_org")
    protected List<Dataroot.TABOrg> tabOrg;
    @XmlAttribute(name = "generated")
    protected String generated;

    /**
     * Gets the value of the tabOrg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tabOrg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTABOrg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dataroot.TABOrg }
     * 
     * 
     */
    public List<Dataroot.TABOrg> getTABOrg() {
        if (tabOrg == null) {
            tabOrg = new ArrayList<Dataroot.TABOrg>();
        }
        return this.tabOrg;
    }

    /**
     * Gets the value of the generated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerated() {
        return generated;
    }

    /**
     * Sets the value of the generated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerated(String value) {
        this.generated = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ID_org" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Nome_organizzazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Telefono_x0020_fisso_x0020__x0028_organizzazione_x0029_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Telefono_x0020_mobile_x0020__x0028_organizzazione_x0029_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Sito_x0020_web_x0020__x0028_organizzazione_x0029_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Email_x0020__x0028_organizzazione_x0029_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="TAB_Attività" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ID_Attività_Contatore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Id_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ID_racc_org" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Nome_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Tipo_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Descrizione_x0020_sintetica_x0020_dell_x0027_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Data_x0020_inizio_x0020_periodo_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Data_x0020_fine_x0020_periodo_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Frequenza" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Orari_x0020__x002F__x0020_periodicità_x002F__x0020_turni_x0020_di_x0020_svolgimento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="L_x0027_attività_x0020_si_x0020_svolge_x0020_nei_x0020_seguenti_x0020_giorni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Sede_x002F_i_x0020_presso_x0020_cui_x0020_si_x0020_svolgerà_x0020_l_x0027_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Tipo_x0020_di_x0020_attività_x0020__x0028_diurna_x002F_residenziale_x0029_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Tipo_x0020_di_x0020_costo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Specifiche_x0020_sul_x0020_costo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Fascia_x002F_e_x0020_di_x0020_età_x0020_destinatari" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Note_x0020_su_x0020_età_x0020_dei_x0020_destinatari" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Vincoli_x0020_di_x0020_residenza_x0020_dei_x0020_destinatari" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Referenti_x0020_che_x0020_possono_x0020_fornire_x0020_informazioni_x0020_su_x0020_questa_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Modalità_x0020_e_x0020_tempi_x0020_di_x0020_iscrizione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="L_x0027_attività_x0020_è_x0020_marchiata_x0020__x0022_Family_x0020_in_x0020_Trentino_x0022__x003F_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Scheda" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="TAb_territorio" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ID_Tab_Comuni_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="ID_RACCORDO_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Comuni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Comunità_valle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="TB_mese" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ID_Mese" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="ID_RACCORDO_Attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Giugno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Luglio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Agosto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Settembre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "idOrg",
        "nomeOrganizzazione",
        "telefonoX0020FissoX0020X0028OrganizzazioneX0029",
        "telefonoX0020MobileX0020X0028OrganizzazioneX0029",
        "sitoX0020WebX0020X0028OrganizzazioneX0029",
        "emailX0020X0028OrganizzazioneX0029",
        "tabAttivit\u00e0"
    })
    public static class TABOrg {

        @XmlElement(name = "ID")
        protected String id;
        @XmlElement(name = "ID_org")
        protected String idOrg;
        @XmlElement(name = "Nome_organizzazione")
        protected String nomeOrganizzazione;
        @XmlElement(name = "Telefono_x0020_fisso_x0020__x0028_organizzazione_x0029_")
        protected String telefonoX0020FissoX0020X0028OrganizzazioneX0029;
        @XmlElement(name = "Telefono_x0020_mobile_x0020__x0028_organizzazione_x0029_")
        protected String telefonoX0020MobileX0020X0028OrganizzazioneX0029;
        @XmlElement(name = "Sito_x0020_web_x0020__x0028_organizzazione_x0029_")
        protected String sitoX0020WebX0020X0028OrganizzazioneX0029;
        @XmlElement(name = "Email_x0020__x0028_organizzazione_x0029_")
        protected String emailX0020X0028OrganizzazioneX0029;
        @XmlElement(name = "TAB_Attivit\u00e0")
        protected List<Dataroot.TABOrg.TABAttività> tabAttività;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the idOrg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIDOrg() {
            return idOrg;
        }

        /**
         * Sets the value of the idOrg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIDOrg(String value) {
            this.idOrg = value;
        }

        /**
         * Gets the value of the nomeOrganizzazione property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNomeOrganizzazione() {
            return nomeOrganizzazione;
        }

        /**
         * Sets the value of the nomeOrganizzazione property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNomeOrganizzazione(String value) {
            this.nomeOrganizzazione = value;
        }

        /**
         * Gets the value of the telefonoX0020FissoX0020X0028OrganizzazioneX0029 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelefonoX0020FissoX0020X0028OrganizzazioneX0029() {
            return telefonoX0020FissoX0020X0028OrganizzazioneX0029;
        }

        /**
         * Sets the value of the telefonoX0020FissoX0020X0028OrganizzazioneX0029 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelefonoX0020FissoX0020X0028OrganizzazioneX0029(String value) {
            this.telefonoX0020FissoX0020X0028OrganizzazioneX0029 = value;
        }

        /**
         * Gets the value of the telefonoX0020MobileX0020X0028OrganizzazioneX0029 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelefonoX0020MobileX0020X0028OrganizzazioneX0029() {
            return telefonoX0020MobileX0020X0028OrganizzazioneX0029;
        }

        /**
         * Sets the value of the telefonoX0020MobileX0020X0028OrganizzazioneX0029 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelefonoX0020MobileX0020X0028OrganizzazioneX0029(String value) {
            this.telefonoX0020MobileX0020X0028OrganizzazioneX0029 = value;
        }

        /**
         * Gets the value of the sitoX0020WebX0020X0028OrganizzazioneX0029 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSitoX0020WebX0020X0028OrganizzazioneX0029() {
            return sitoX0020WebX0020X0028OrganizzazioneX0029;
        }

        /**
         * Sets the value of the sitoX0020WebX0020X0028OrganizzazioneX0029 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSitoX0020WebX0020X0028OrganizzazioneX0029(String value) {
            this.sitoX0020WebX0020X0028OrganizzazioneX0029 = value;
        }

        /**
         * Gets the value of the emailX0020X0028OrganizzazioneX0029 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmailX0020X0028OrganizzazioneX0029() {
            return emailX0020X0028OrganizzazioneX0029;
        }

        /**
         * Sets the value of the emailX0020X0028OrganizzazioneX0029 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmailX0020X0028OrganizzazioneX0029(String value) {
            this.emailX0020X0028OrganizzazioneX0029 = value;
        }

        /**
         * Gets the value of the tabAttività property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tabAttività property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTABAttività().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dataroot.TABOrg.TABAttività }
         * 
         * 
         */
        public List<Dataroot.TABOrg.TABAttività> getTABAttività() {
            if (tabAttività == null) {
                tabAttività = new ArrayList<Dataroot.TABOrg.TABAttività>();
            }
            return this.tabAttività;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ID_Attività_Contatore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Id_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ID_racc_org" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Nome_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Tipo_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Descrizione_x0020_sintetica_x0020_dell_x0027_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Data_x0020_inizio_x0020_periodo_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Data_x0020_fine_x0020_periodo_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Frequenza" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Orari_x0020__x002F__x0020_periodicità_x002F__x0020_turni_x0020_di_x0020_svolgimento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="L_x0027_attività_x0020_si_x0020_svolge_x0020_nei_x0020_seguenti_x0020_giorni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Sede_x002F_i_x0020_presso_x0020_cui_x0020_si_x0020_svolgerà_x0020_l_x0027_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Tipo_x0020_di_x0020_attività_x0020__x0028_diurna_x002F_residenziale_x0029_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Tipo_x0020_di_x0020_costo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Specifiche_x0020_sul_x0020_costo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Fascia_x002F_e_x0020_di_x0020_età_x0020_destinatari" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Note_x0020_su_x0020_età_x0020_dei_x0020_destinatari" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Vincoli_x0020_di_x0020_residenza_x0020_dei_x0020_destinatari" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Referenti_x0020_che_x0020_possono_x0020_fornire_x0020_informazioni_x0020_su_x0020_questa_x0020_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Modalità_x0020_e_x0020_tempi_x0020_di_x0020_iscrizione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="L_x0027_attività_x0020_è_x0020_marchiata_x0020__x0022_Family_x0020_in_x0020_Trentino_x0022__x003F_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Scheda" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="TAb_territorio" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ID_Tab_Comuni_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="ID_RACCORDO_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Comuni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Comunità_valle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="TB_mese" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ID_Mese" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="ID_RACCORDO_Attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Giugno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Luglio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Agosto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Settembre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idAttivit\u00e0Contatore",
            "idAttivit\u00e0",
            "idRaccOrg",
            "nomeX0020Attivit\u00e0",
            "tipoX0020Attivit\u00e0",
            "descrizioneX0020SinteticaX0020DellX0027Attivit\u00e0",
            "dataX0020InizioX0020PeriodoX0020Attivit\u00e0",
            "dataX0020FineX0020PeriodoX0020Attivit\u00e0",
            "frequenza",
            "orariX0020X002FX0020Periodicit\u00e0X002FX0020TurniX0020DiX0020Svolgimento",
            "lx0027Attivit\u00e0X0020SiX0020SvolgeX0020NeiX0020SeguentiX0020Giorni",
            "sedeX002FIX0020PressoX0020CuiX0020SiX0020Svolger\u00e0X0020LX0027Attivit\u00e0",
            "tipoX0020DiX0020Attivit\u00e0X0020X0028DiurnaX002FResidenzialeX0029",
            "tipoX0020DiX0020Costo",
            "specificheX0020SulX0020Costo",
            "fasciaX002FEX0020DiX0020Et\u00e0X0020Destinatari",
            "noteX0020SuX0020Et\u00e0X0020DeiX0020Destinatari",
            "vincoliX0020DiX0020ResidenzaX0020DeiX0020Destinatari",
            "referentiX0020CheX0020PossonoX0020FornireX0020InformazioniX0020SuX0020QuestaX0020Attivit\u00e0",
            "modalit\u00e0X0020EX0020TempiX0020DiX0020Iscrizione",
            "lx0027Attivit\u00e0X0020\u00c8X0020MarchiataX0020X0022FamilyX0020InX0020TrentinoX0022X003F",
            "scheda",
            "tAbTerritorio",
            "tbMese"
        })
        public static class TABAttività {

            @XmlElement(name = "ID_Attivit\u00e0_Contatore")
            protected String idAttivitàContatore;
            @XmlElement(name = "Id_attivit\u00e0")
            protected String idAttività;
            @XmlElement(name = "ID_racc_org")
            protected String idRaccOrg;
            @XmlElement(name = "Nome_x0020_attivit\u00e0")
            protected String nomeX0020Attività;
            @XmlElement(name = "Tipo_x0020_attivit\u00e0")
            protected String tipoX0020Attività;
            @XmlElement(name = "Descrizione_x0020_sintetica_x0020_dell_x0027_attivit\u00e0")
            protected String descrizioneX0020SinteticaX0020DellX0027Attività;
            @XmlElement(name = "Data_x0020_inizio_x0020_periodo_x0020_attivit\u00e0")
            protected String dataX0020InizioX0020PeriodoX0020Attività;
            @XmlElement(name = "Data_x0020_fine_x0020_periodo_x0020_attivit\u00e0")
            protected String dataX0020FineX0020PeriodoX0020Attività;
            @XmlElement(name = "Frequenza")
            protected String frequenza;
            @XmlElement(name = "Orari_x0020__x002F__x0020_periodicit\u00e0_x002F__x0020_turni_x0020_di_x0020_svolgimento")
            protected String orariX0020X002FX0020PeriodicitàX002FX0020TurniX0020DiX0020Svolgimento;
            @XmlElement(name = "L_x0027_attivit\u00e0_x0020_si_x0020_svolge_x0020_nei_x0020_seguenti_x0020_giorni")
            protected String lx0027AttivitàX0020SiX0020SvolgeX0020NeiX0020SeguentiX0020Giorni;
            @XmlElement(name = "Sede_x002F_i_x0020_presso_x0020_cui_x0020_si_x0020_svolger\u00e0_x0020_l_x0027_attivit\u00e0")
            protected String sedeX002FIX0020PressoX0020CuiX0020SiX0020SvolgeràX0020LX0027Attività;
            @XmlElement(name = "Tipo_x0020_di_x0020_attivit\u00e0_x0020__x0028_diurna_x002F_residenziale_x0029_")
            protected String tipoX0020DiX0020AttivitàX0020X0028DiurnaX002FResidenzialeX0029;
            @XmlElement(name = "Tipo_x0020_di_x0020_costo")
            protected String tipoX0020DiX0020Costo;
            @XmlElement(name = "Specifiche_x0020_sul_x0020_costo")
            protected String specificheX0020SulX0020Costo;
            @XmlElement(name = "Fascia_x002F_e_x0020_di_x0020_et\u00e0_x0020_destinatari")
            protected String fasciaX002FEX0020DiX0020EtàX0020Destinatari;
            @XmlElement(name = "Note_x0020_su_x0020_et\u00e0_x0020_dei_x0020_destinatari")
            protected String noteX0020SuX0020EtàX0020DeiX0020Destinatari;
            @XmlElement(name = "Vincoli_x0020_di_x0020_residenza_x0020_dei_x0020_destinatari")
            protected String vincoliX0020DiX0020ResidenzaX0020DeiX0020Destinatari;
            @XmlElement(name = "Referenti_x0020_che_x0020_possono_x0020_fornire_x0020_informazioni_x0020_su_x0020_questa_x0020_attivit\u00e0")
            protected String referentiX0020CheX0020PossonoX0020FornireX0020InformazioniX0020SuX0020QuestaX0020Attività;
            @XmlElement(name = "Modalit\u00e0_x0020_e_x0020_tempi_x0020_di_x0020_iscrizione")
            protected String modalitàX0020EX0020TempiX0020DiX0020Iscrizione;
            @XmlElement(name = "L_x0027_attivit\u00e0_x0020_\u00e8_x0020_marchiata_x0020__x0022_Family_x0020_in_x0020_Trentino_x0022__x003F_")
            protected String lx0027AttivitàX0020ÈX0020MarchiataX0020X0022FamilyX0020InX0020TrentinoX0022X003F;
            @XmlElement(name = "Scheda")
            protected String scheda;
            @XmlElement(name = "TAb_territorio")
            protected List<Dataroot.TABOrg.TABAttività.TAbTerritorio> tAbTerritorio;
            @XmlElement(name = "TB_mese")
            protected List<Dataroot.TABOrg.TABAttività.TBMese> tbMese;

            /**
             * Gets the value of the idAttivitàContatore property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIDAttivitàContatore() {
                return idAttivitàContatore;
            }

            /**
             * Sets the value of the idAttivitàContatore property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIDAttivitàContatore(String value) {
                this.idAttivitàContatore = value;
            }

            /**
             * Gets the value of the idAttività property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdAttività() {
                return idAttività;
            }

            /**
             * Sets the value of the idAttività property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdAttività(String value) {
                this.idAttività = value;
            }

            /**
             * Gets the value of the idRaccOrg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIDRaccOrg() {
                return idRaccOrg;
            }

            /**
             * Sets the value of the idRaccOrg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIDRaccOrg(String value) {
                this.idRaccOrg = value;
            }

            /**
             * Gets the value of the nomeX0020Attività property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNomeX0020Attività() {
                return nomeX0020Attività;
            }

            /**
             * Sets the value of the nomeX0020Attività property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNomeX0020Attività(String value) {
                this.nomeX0020Attività = value;
            }

            /**
             * Gets the value of the tipoX0020Attività property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipoX0020Attività() {
                return tipoX0020Attività;
            }

            /**
             * Sets the value of the tipoX0020Attività property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipoX0020Attività(String value) {
                this.tipoX0020Attività = value;
            }

            /**
             * Gets the value of the descrizioneX0020SinteticaX0020DellX0027Attività property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescrizioneX0020SinteticaX0020DellX0027Attività() {
                return descrizioneX0020SinteticaX0020DellX0027Attività;
            }

            /**
             * Sets the value of the descrizioneX0020SinteticaX0020DellX0027Attività property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescrizioneX0020SinteticaX0020DellX0027Attività(String value) {
                this.descrizioneX0020SinteticaX0020DellX0027Attività = value;
            }

            /**
             * Gets the value of the dataX0020InizioX0020PeriodoX0020Attività property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDataX0020InizioX0020PeriodoX0020Attività() {
                return dataX0020InizioX0020PeriodoX0020Attività;
            }

            /**
             * Sets the value of the dataX0020InizioX0020PeriodoX0020Attività property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDataX0020InizioX0020PeriodoX0020Attività(String value) {
                this.dataX0020InizioX0020PeriodoX0020Attività = value;
            }

            /**
             * Gets the value of the dataX0020FineX0020PeriodoX0020Attività property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDataX0020FineX0020PeriodoX0020Attività() {
                return dataX0020FineX0020PeriodoX0020Attività;
            }

            /**
             * Sets the value of the dataX0020FineX0020PeriodoX0020Attività property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDataX0020FineX0020PeriodoX0020Attività(String value) {
                this.dataX0020FineX0020PeriodoX0020Attività = value;
            }

            /**
             * Gets the value of the frequenza property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFrequenza() {
                return frequenza;
            }

            /**
             * Sets the value of the frequenza property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFrequenza(String value) {
                this.frequenza = value;
            }

            /**
             * Gets the value of the orariX0020X002FX0020PeriodicitàX002FX0020TurniX0020DiX0020Svolgimento property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrariX0020X002FX0020PeriodicitàX002FX0020TurniX0020DiX0020Svolgimento() {
                return orariX0020X002FX0020PeriodicitàX002FX0020TurniX0020DiX0020Svolgimento;
            }

            /**
             * Sets the value of the orariX0020X002FX0020PeriodicitàX002FX0020TurniX0020DiX0020Svolgimento property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrariX0020X002FX0020PeriodicitàX002FX0020TurniX0020DiX0020Svolgimento(String value) {
                this.orariX0020X002FX0020PeriodicitàX002FX0020TurniX0020DiX0020Svolgimento = value;
            }

            /**
             * Gets the value of the lx0027AttivitàX0020SiX0020SvolgeX0020NeiX0020SeguentiX0020Giorni property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLX0027AttivitàX0020SiX0020SvolgeX0020NeiX0020SeguentiX0020Giorni() {
                return lx0027AttivitàX0020SiX0020SvolgeX0020NeiX0020SeguentiX0020Giorni;
            }

            /**
             * Sets the value of the lx0027AttivitàX0020SiX0020SvolgeX0020NeiX0020SeguentiX0020Giorni property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLX0027AttivitàX0020SiX0020SvolgeX0020NeiX0020SeguentiX0020Giorni(String value) {
                this.lx0027AttivitàX0020SiX0020SvolgeX0020NeiX0020SeguentiX0020Giorni = value;
            }

            /**
             * Gets the value of the sedeX002FIX0020PressoX0020CuiX0020SiX0020SvolgeràX0020LX0027Attività property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSedeX002FIX0020PressoX0020CuiX0020SiX0020SvolgeràX0020LX0027Attività() {
                return sedeX002FIX0020PressoX0020CuiX0020SiX0020SvolgeràX0020LX0027Attività;
            }

            /**
             * Sets the value of the sedeX002FIX0020PressoX0020CuiX0020SiX0020SvolgeràX0020LX0027Attività property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSedeX002FIX0020PressoX0020CuiX0020SiX0020SvolgeràX0020LX0027Attività(String value) {
                this.sedeX002FIX0020PressoX0020CuiX0020SiX0020SvolgeràX0020LX0027Attività = value;
            }

            /**
             * Gets the value of the tipoX0020DiX0020AttivitàX0020X0028DiurnaX002FResidenzialeX0029 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipoX0020DiX0020AttivitàX0020X0028DiurnaX002FResidenzialeX0029() {
                return tipoX0020DiX0020AttivitàX0020X0028DiurnaX002FResidenzialeX0029;
            }

            /**
             * Sets the value of the tipoX0020DiX0020AttivitàX0020X0028DiurnaX002FResidenzialeX0029 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipoX0020DiX0020AttivitàX0020X0028DiurnaX002FResidenzialeX0029(String value) {
                this.tipoX0020DiX0020AttivitàX0020X0028DiurnaX002FResidenzialeX0029 = value;
            }

            /**
             * Gets the value of the tipoX0020DiX0020Costo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipoX0020DiX0020Costo() {
                return tipoX0020DiX0020Costo;
            }

            /**
             * Sets the value of the tipoX0020DiX0020Costo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipoX0020DiX0020Costo(String value) {
                this.tipoX0020DiX0020Costo = value;
            }

            /**
             * Gets the value of the specificheX0020SulX0020Costo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSpecificheX0020SulX0020Costo() {
                return specificheX0020SulX0020Costo;
            }

            /**
             * Sets the value of the specificheX0020SulX0020Costo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSpecificheX0020SulX0020Costo(String value) {
                this.specificheX0020SulX0020Costo = value;
            }

            /**
             * Gets the value of the fasciaX002FEX0020DiX0020EtàX0020Destinatari property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFasciaX002FEX0020DiX0020EtàX0020Destinatari() {
                return fasciaX002FEX0020DiX0020EtàX0020Destinatari;
            }

            /**
             * Sets the value of the fasciaX002FEX0020DiX0020EtàX0020Destinatari property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFasciaX002FEX0020DiX0020EtàX0020Destinatari(String value) {
                this.fasciaX002FEX0020DiX0020EtàX0020Destinatari = value;
            }

            /**
             * Gets the value of the noteX0020SuX0020EtàX0020DeiX0020Destinatari property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNoteX0020SuX0020EtàX0020DeiX0020Destinatari() {
                return noteX0020SuX0020EtàX0020DeiX0020Destinatari;
            }

            /**
             * Sets the value of the noteX0020SuX0020EtàX0020DeiX0020Destinatari property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNoteX0020SuX0020EtàX0020DeiX0020Destinatari(String value) {
                this.noteX0020SuX0020EtàX0020DeiX0020Destinatari = value;
            }

            /**
             * Gets the value of the vincoliX0020DiX0020ResidenzaX0020DeiX0020Destinatari property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVincoliX0020DiX0020ResidenzaX0020DeiX0020Destinatari() {
                return vincoliX0020DiX0020ResidenzaX0020DeiX0020Destinatari;
            }

            /**
             * Sets the value of the vincoliX0020DiX0020ResidenzaX0020DeiX0020Destinatari property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVincoliX0020DiX0020ResidenzaX0020DeiX0020Destinatari(String value) {
                this.vincoliX0020DiX0020ResidenzaX0020DeiX0020Destinatari = value;
            }

            /**
             * Gets the value of the referentiX0020CheX0020PossonoX0020FornireX0020InformazioniX0020SuX0020QuestaX0020Attività property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReferentiX0020CheX0020PossonoX0020FornireX0020InformazioniX0020SuX0020QuestaX0020Attività() {
                return referentiX0020CheX0020PossonoX0020FornireX0020InformazioniX0020SuX0020QuestaX0020Attività;
            }

            /**
             * Sets the value of the referentiX0020CheX0020PossonoX0020FornireX0020InformazioniX0020SuX0020QuestaX0020Attività property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReferentiX0020CheX0020PossonoX0020FornireX0020InformazioniX0020SuX0020QuestaX0020Attività(String value) {
                this.referentiX0020CheX0020PossonoX0020FornireX0020InformazioniX0020SuX0020QuestaX0020Attività = value;
            }

            /**
             * Gets the value of the modalitàX0020EX0020TempiX0020DiX0020Iscrizione property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getModalitàX0020EX0020TempiX0020DiX0020Iscrizione() {
                return modalitàX0020EX0020TempiX0020DiX0020Iscrizione;
            }

            /**
             * Sets the value of the modalitàX0020EX0020TempiX0020DiX0020Iscrizione property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setModalitàX0020EX0020TempiX0020DiX0020Iscrizione(String value) {
                this.modalitàX0020EX0020TempiX0020DiX0020Iscrizione = value;
            }

            /**
             * Gets the value of the lx0027AttivitàX0020ÈX0020MarchiataX0020X0022FamilyX0020InX0020TrentinoX0022X003F property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLX0027AttivitàX0020ÈX0020MarchiataX0020X0022FamilyX0020InX0020TrentinoX0022X003F() {
                return lx0027AttivitàX0020ÈX0020MarchiataX0020X0022FamilyX0020InX0020TrentinoX0022X003F;
            }

            /**
             * Sets the value of the lx0027AttivitàX0020ÈX0020MarchiataX0020X0022FamilyX0020InX0020TrentinoX0022X003F property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLX0027AttivitàX0020ÈX0020MarchiataX0020X0022FamilyX0020InX0020TrentinoX0022X003F(String value) {
                this.lx0027AttivitàX0020ÈX0020MarchiataX0020X0022FamilyX0020InX0020TrentinoX0022X003F = value;
            }

            /**
             * Gets the value of the scheda property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getScheda() {
                return scheda;
            }

            /**
             * Sets the value of the scheda property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setScheda(String value) {
                this.scheda = value;
            }

            /**
             * Gets the value of the tAbTerritorio property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the tAbTerritorio property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTAbTerritorio().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Dataroot.TABOrg.TABAttività.TAbTerritorio }
             * 
             * 
             */
            public List<Dataroot.TABOrg.TABAttività.TAbTerritorio> getTAbTerritorio() {
                if (tAbTerritorio == null) {
                    tAbTerritorio = new ArrayList<Dataroot.TABOrg.TABAttività.TAbTerritorio>();
                }
                return this.tAbTerritorio;
            }

            /**
             * Gets the value of the tbMese property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the tbMese property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTBMese().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Dataroot.TABOrg.TABAttività.TBMese }
             * 
             * 
             */
            public List<Dataroot.TABOrg.TABAttività.TBMese> getTBMese() {
                if (tbMese == null) {
                    tbMese = new ArrayList<Dataroot.TABOrg.TABAttività.TBMese>();
                }
                return this.tbMese;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ID_Tab_Comuni_" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="ID_RACCORDO_attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Comuni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Comunità_valle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "idTabComuni",
                "idraccordoAttivit\u00e0",
                "comuni",
                "comunit\u00e0Valle"
            })
            public static class TAbTerritorio {

                @XmlElement(name = "ID_Tab_Comuni_")
                protected String idTabComuni;
                @XmlElement(name = "ID_RACCORDO_attivit\u00e0")
                protected String idraccordoAttività;
                @XmlElement(name = "Comuni")
                protected String comuni;
                @XmlElement(name = "Comunit\u00e0_valle")
                protected String comunitàValle;

                /**
                 * Gets the value of the idTabComuni property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIDTabComuni() {
                    return idTabComuni;
                }

                /**
                 * Sets the value of the idTabComuni property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIDTabComuni(String value) {
                    this.idTabComuni = value;
                }

                /**
                 * Gets the value of the idraccordoAttività property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIDRACCORDOAttività() {
                    return idraccordoAttività;
                }

                /**
                 * Sets the value of the idraccordoAttività property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIDRACCORDOAttività(String value) {
                    this.idraccordoAttività = value;
                }

                /**
                 * Gets the value of the comuni property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getComuni() {
                    return comuni;
                }

                /**
                 * Sets the value of the comuni property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setComuni(String value) {
                    this.comuni = value;
                }

                /**
                 * Gets the value of the comunitàValle property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getComunitàValle() {
                    return comunitàValle;
                }

                /**
                 * Sets the value of the comunitàValle property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setComunitàValle(String value) {
                    this.comunitàValle = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ID_Mese" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="ID_RACCORDO_Attività" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Giugno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Luglio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Agosto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Settembre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "idMese",
                "idraccordoAttivit\u00e0",
                "giugno",
                "luglio",
                "agosto",
                "settembre"
            })
            public static class TBMese {

                @XmlElement(name = "ID_Mese")
                protected String idMese;
                @XmlElement(name = "ID_RACCORDO_Attivit\u00e0")
                protected String idraccordoAttività;
                @XmlElement(name = "Giugno")
                protected String giugno;
                @XmlElement(name = "Luglio")
                protected String luglio;
                @XmlElement(name = "Agosto")
                protected String agosto;
                @XmlElement(name = "Settembre")
                protected String settembre;

                /**
                 * Gets the value of the idMese property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIDMese() {
                    return idMese;
                }

                /**
                 * Sets the value of the idMese property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIDMese(String value) {
                    this.idMese = value;
                }

                /**
                 * Gets the value of the idraccordoAttività property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIDRACCORDOAttività() {
                    return idraccordoAttività;
                }

                /**
                 * Sets the value of the idraccordoAttività property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIDRACCORDOAttività(String value) {
                    this.idraccordoAttività = value;
                }

                /**
                 * Gets the value of the giugno property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGiugno() {
                    return giugno;
                }

                /**
                 * Sets the value of the giugno property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGiugno(String value) {
                    this.giugno = value;
                }

                /**
                 * Gets the value of the luglio property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLuglio() {
                    return luglio;
                }

                /**
                 * Sets the value of the luglio property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLuglio(String value) {
                    this.luglio = value;
                }

                /**
                 * Gets the value of the agosto property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAgosto() {
                    return agosto;
                }

                /**
                 * Sets the value of the agosto property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAgosto(String value) {
                    this.agosto = value;
                }

                /**
                 * Gets the value of the settembre property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSettembre() {
                    return settembre;
                }

                /**
                 * Sets the value of the settembre property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSettembre(String value) {
                    this.settembre = value;
                }

            }

        }

    }

}
