//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.16 at 08:55:09 PM CEST 
//


package eu.trentorise.smartcampus.service.trentinofamiglia.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.trentorise.smartcampus.service.trentinofamiglia.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.trentorise.smartcampus.service.trentinofamiglia.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link Dataroot.TABOrg.TABAttività.TAbTerritorio }
     * 
     */
    public Dataroot.TABOrg.TABAttività.TAbTerritorio createDatarootTABOrgTABAttivitàTAbTerritorio() {
        return new Dataroot.TABOrg.TABAttività.TAbTerritorio();
    }

    /**
     * Create an instance of {@link Dataroot.TABOrg.TABAttività.TBMese }
     * 
     */
    public Dataroot.TABOrg.TABAttività.TBMese createDatarootTABOrgTABAttivitàTBMese() {
        return new Dataroot.TABOrg.TABAttività.TBMese();
    }

    /**
     * Create an instance of {@link Dataroot.TABOrg }
     * 
     */
    public Dataroot.TABOrg createDatarootTABOrg() {
        return new Dataroot.TABOrg();
    }

    /**
     * Create an instance of {@link Dataroot.TABOrg.TABAttività }
     * 
     */
    public Dataroot.TABOrg.TABAttività createDatarootTABOrgTABAttività() {
        return new Dataroot.TABOrg.TABAttività();
    }

    /**
     * Create an instance of {@link Dataroot }
     * 
     */
    public Dataroot createDataroot() {
        return new Dataroot();
    }

}
