//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 10:17:18 AM CET 
//


package eu.trentorise.smartcampus.service.trentinofamiglia.garda.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="item" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="pubDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="testobreve" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="luogodisvolgimento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="localita">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="datainizio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="datafine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="categoria" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="importante" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="coordinate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                             &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="datatestuale" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ora" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="oratestuale" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="prezzo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="gratuito" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item"
})
@XmlRootElement(name = "events")
public class Events {

    protected List<Events.Item> item;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Events.Item }
     * 
     * 
     */
    public List<Events.Item> getItem() {
        if (item == null) {
            item = new ArrayList<Events.Item>();
        }
        return this.item;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="pubDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="testobreve" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="luogodisvolgimento" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="localita">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="datainizio" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="datafine" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="categoria" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="importante" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="coordinate">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *                   &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="datatestuale" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ora" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="oratestuale" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="prezzo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="gratuito" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title",
        "description",
        "link",
        "pubDate",
        "guid",
        "testobreve",
        "luogodisvolgimento",
        "localita",
        "datainizio",
        "datafine",
        "categoria",
        "importante",
        "coordinate",
        "datatestuale",
        "ora",
        "oratestuale",
        "prezzo",
        "gratuito"
    })
    public static class Item {

        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String link;
        @XmlElement(required = true)
        protected String pubDate;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String guid;
        @XmlElement(required = true)
        protected String testobreve;
        @XmlElement(required = true)
        protected String luogodisvolgimento;
        @XmlElement(required = true)
        protected Events.Item.Localita localita;
        @XmlElement(required = true)
        protected String datainizio;
        @XmlElement(required = true)
        protected String datafine;
        @XmlElement(required = true)
        protected String categoria;
        @XmlElement(required = true)
        protected String importante;
        @XmlElement(required = true)
        protected Events.Item.Coordinate coordinate;
        @XmlElement(required = true)
        protected String datatestuale;
        @XmlElement(required = true)
        protected String ora;
        @XmlElement(required = true)
        protected String oratestuale;
        @XmlElement(required = true)
        protected String prezzo;
        @XmlElement(required = true)
        protected String gratuito;

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the link property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLink(String value) {
            this.link = value;
        }

        /**
         * Gets the value of the pubDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPubDate() {
            return pubDate;
        }

        /**
         * Sets the value of the pubDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPubDate(String value) {
            this.pubDate = value;
        }

        /**
         * Gets the value of the guid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGuid() {
            return guid;
        }

        /**
         * Sets the value of the guid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGuid(String value) {
            this.guid = value;
        }

        /**
         * Gets the value of the testobreve property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTestobreve() {
            return testobreve;
        }

        /**
         * Sets the value of the testobreve property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTestobreve(String value) {
            this.testobreve = value;
        }

        /**
         * Gets the value of the luogodisvolgimento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLuogodisvolgimento() {
            return luogodisvolgimento;
        }

        /**
         * Sets the value of the luogodisvolgimento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLuogodisvolgimento(String value) {
            this.luogodisvolgimento = value;
        }

        /**
         * Gets the value of the localita property.
         * 
         * @return
         *     possible object is
         *     {@link Events.Item.Localita }
         *     
         */
        public Events.Item.Localita getLocalita() {
            return localita;
        }

        /**
         * Sets the value of the localita property.
         * 
         * @param value
         *     allowed object is
         *     {@link Events.Item.Localita }
         *     
         */
        public void setLocalita(Events.Item.Localita value) {
            this.localita = value;
        }

        /**
         * Gets the value of the datainizio property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatainizio() {
            return datainizio;
        }

        /**
         * Sets the value of the datainizio property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatainizio(String value) {
            this.datainizio = value;
        }

        /**
         * Gets the value of the datafine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatafine() {
            return datafine;
        }

        /**
         * Sets the value of the datafine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatafine(String value) {
            this.datafine = value;
        }

        /**
         * Gets the value of the categoria property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategoria() {
            return categoria;
        }

        /**
         * Sets the value of the categoria property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategoria(String value) {
            this.categoria = value;
        }

        /**
         * Gets the value of the importante property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImportante() {
            return importante;
        }

        /**
         * Sets the value of the importante property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImportante(String value) {
            this.importante = value;
        }

        /**
         * Gets the value of the coordinate property.
         * 
         * @return
         *     possible object is
         *     {@link Events.Item.Coordinate }
         *     
         */
        public Events.Item.Coordinate getCoordinate() {
            return coordinate;
        }

        /**
         * Sets the value of the coordinate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Events.Item.Coordinate }
         *     
         */
        public void setCoordinate(Events.Item.Coordinate value) {
            this.coordinate = value;
        }

        /**
         * Gets the value of the datatestuale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatatestuale() {
            return datatestuale;
        }

        /**
         * Sets the value of the datatestuale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatatestuale(String value) {
            this.datatestuale = value;
        }

        /**
         * Gets the value of the ora property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOra() {
            return ora;
        }

        /**
         * Sets the value of the ora property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOra(String value) {
            this.ora = value;
        }

        /**
         * Gets the value of the oratestuale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOratestuale() {
            return oratestuale;
        }

        /**
         * Sets the value of the oratestuale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOratestuale(String value) {
            this.oratestuale = value;
        }

        /**
         * Gets the value of the prezzo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrezzo() {
            return prezzo;
        }

        /**
         * Sets the value of the prezzo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrezzo(String value) {
            this.prezzo = value;
        }

        /**
         * Gets the value of the gratuito property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGratuito() {
            return gratuito;
        }

        /**
         * Sets the value of the gratuito property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGratuito(String value) {
            this.gratuito = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
         *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "x",
            "y"
        })
        public static class Coordinate {

            protected Float x;
            protected Float y;

            /**
             * Gets the value of the x property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getX() {
                return x;
            }

            /**
             * Sets the value of the x property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setX(Float value) {
                this.x = value;
            }

            /**
             * Gets the value of the y property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getY() {
                return y;
            }

            /**
             * Sets the value of the y property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setY(Float value) {
                this.y = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "item"
        })
        public static class Localita {

            protected String item;

            /**
             * Gets the value of the item property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getItem() {
                return item;
            }

            /**
             * Sets the value of the item property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setItem(String value) {
                this.item = value;
            }

        }

    }

}
