//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.25 at 11:40:18 AM CEST 
//


package eu.trentorise.smartcampus.service.trentinofamiglia.dossier.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DossierPoliticheFam_IntEco_DataSet" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IdIntervento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Tipologia_x0020_Intervento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ChiPuòRichiedere" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CosaFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PerSaperneDiPiù" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="generated" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dossierPoliticheFamIntEcoDataSet"
})
@XmlRootElement(name = "dataroot")
public class Dataroot {

    @XmlElement(name = "DossierPoliticheFam_IntEco_DataSet")
    protected List<Dataroot.DossierPoliticheFamIntEcoDataSet> dossierPoliticheFamIntEcoDataSet;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar generated;

    /**
     * Gets the value of the dossierPoliticheFamIntEcoDataSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dossierPoliticheFamIntEcoDataSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDossierPoliticheFamIntEcoDataSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dataroot.DossierPoliticheFamIntEcoDataSet }
     * 
     * 
     */
    public List<Dataroot.DossierPoliticheFamIntEcoDataSet> getDossierPoliticheFamIntEcoDataSet() {
        if (dossierPoliticheFamIntEcoDataSet == null) {
            dossierPoliticheFamIntEcoDataSet = new ArrayList<Dataroot.DossierPoliticheFamIntEcoDataSet>();
        }
        return this.dossierPoliticheFamIntEcoDataSet;
    }

    /**
     * Gets the value of the generated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGenerated() {
        return generated;
    }

    /**
     * Sets the value of the generated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGenerated(XMLGregorianCalendar value) {
        this.generated = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IdIntervento" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Titolo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Tipologia_x0020_Intervento" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ChiPuòRichiedere" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CosaFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PerSaperneDiPiù" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idIntervento",
        "titolo",
        "tipologiaX0020Intervento",
        "descrizione",
        "chiPu\u00f2Richiedere",
        "cosaFare",
        "perSaperneDiPi\u00f9"
    })
    public static class DossierPoliticheFamIntEcoDataSet {

        @XmlElement(name = "IdIntervento", required = true)
        protected String idIntervento;
        @XmlElement(name = "Titolo")
        protected String titolo;
        @XmlElement(name = "Tipologia_x0020_Intervento", required = true)
        protected String tipologiaX0020Intervento;
        @XmlElement(name = "Descrizione")
        protected String descrizione;
        @XmlElement(name = "ChiPu\u00f2Richiedere")
        protected String chiPuòRichiedere;
        @XmlElement(name = "CosaFare")
        protected String cosaFare;
        @XmlElement(name = "PerSaperneDiPi\u00f9")
        protected String perSaperneDiPiù;

        /**
         * Gets the value of the idIntervento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdIntervento() {
            return idIntervento;
        }

        /**
         * Sets the value of the idIntervento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdIntervento(String value) {
            this.idIntervento = value;
        }

        /**
         * Gets the value of the titolo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitolo() {
            return titolo;
        }

        /**
         * Sets the value of the titolo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitolo(String value) {
            this.titolo = value;
        }

        /**
         * Gets the value of the tipologiaX0020Intervento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipologiaX0020Intervento() {
            return tipologiaX0020Intervento;
        }

        /**
         * Sets the value of the tipologiaX0020Intervento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipologiaX0020Intervento(String value) {
            this.tipologiaX0020Intervento = value;
        }

        /**
         * Gets the value of the descrizione property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescrizione() {
            return descrizione;
        }

        /**
         * Sets the value of the descrizione property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescrizione(String value) {
            this.descrizione = value;
        }

        /**
         * Gets the value of the chiPuòRichiedere property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChiPuòRichiedere() {
            return chiPuòRichiedere;
        }

        /**
         * Sets the value of the chiPuòRichiedere property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChiPuòRichiedere(String value) {
            this.chiPuòRichiedere = value;
        }

        /**
         * Gets the value of the cosaFare property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCosaFare() {
            return cosaFare;
        }

        /**
         * Sets the value of the cosaFare property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCosaFare(String value) {
            this.cosaFare = value;
        }

        /**
         * Gets the value of the perSaperneDiPiù property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPerSaperneDiPiù() {
            return perSaperneDiPiù;
        }

        /**
         * Sets the value of the perSaperneDiPiù property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPerSaperneDiPiù(String value) {
            this.perSaperneDiPiù = value;
        }

    }

}
